### ISSUE TITLE
MVP Features Required

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-qunit-codemod#1]
- [x] Use `setupTest` or `setupRenderingTest` based on `integration: true` flag
- [x] Modify tests within a `setupRenderingTest` block to use `async` function
- [x] Add `await` in front of `render` usage in a `setupRenderingTest` tests
- [x] Rewrite `this.render(` to use imported `render` function
- [x] Rewrite `this.clearRender()` to use `await clearRender()`;
- [x] Rewrite `this.container.lookup` usage to `this.owner.lookup`
- [x] Rewrite `this.registry.register` usage to `this.owner.register`
- [x] Rewrite `this.register` usage to `this.owner.register`
- [x] Rewrite `this.inject.service('foo')` usage to `this.foo = this.owner.lookup('service:foo')`
- [x] Rewrite `this._element` usage to `this.element`

**Comment by cibernox** [comment]
Maybe?
- [ ] Rewrite `this.$()` usage to `$(this.element)`?

**Comment by rwjblue** [comment]
@cibernox - The new API still has a `this.$()` if jQuery is present.

**Comment by Turbo87** [comment]
```
TypeError: this.lookup is not a function
```

I suppose you meant `this.container.lookup()` instead of `this.lookup()`?

**Comment by rwjblue** [comment]
@turbo87 - Yes, thank you.

**Comment by cibernox** [comment]
May I 🔒 `Rewrite this.container.lookup usage to this.owner.lookup` for myself?

**Comment by Turbo87** [comment]
@rwjblue should we also try to replace `this.subject()` with something useful?

**Comment by Turbo87** [comment]
```
this.subject = (...args) => this.owner.factoryFor('controller:booking/details').create(...args);
```

in the `beforeEach()` hook seems to work well enough, should be easy to refactor away and simplifies the migration path a little bit. Guess we would have to decide between `factoryFor` and `lookup` depending on the type of module we're testing.

**Comment by cibernox** [comment]
@rwjblue I also call dibs on `Rewrite this.register usage to this.owner.register`

**Comment by cibernox** [comment]
Finished, I also call dibs on `Rewrite this.registry.register usage to this.owner.register`

**Comment by rwjblue** [comment]
Making another issue to track the `this.subject` migration mentioned above...
