### ISSUE TITLE
Needed to manually install jscodeshift

### ISSUE THREAD

**Issue by dgeb** [rwjblue/ember-qunit-codemod#140]
I tried to use this codemod directly in both ways as suggested by the usage instructions:

```
npx ember-qunit-codemod convert-module-for-to-setup-test path/of/files/ or/some**/*glob.js

# or

yarn global add ember-qunit-codemod
ember-qunit-codemod convert-module-for-to-setup-test path/of/files/ or/some**/*glob.js
```

Both approaches resulted in the following error:

```
Error: spawn jscodeshift ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I was able to resolve this by globally installing `jscodeshift`:

```
yarn global add jscodeshift
```

I suppose the binary wasn't available otherwise, even though it is in fact a dependency of `codemod-cli`.

Thought we should discuss to help others avoid this papercut.

**Comment by rwjblue** [comment]
Thanks for reporting, most likely need to fix this in codemod-cli. I submitted https://github.com/rwjblue/codemod-cli/pull/48 as a first pass...

**Comment by dgeb** [comment]
Ah, that looks like it has potential 👍  Thanks for following up @rwjblue!
