### ISSUE TITLE
Error: You should not call `create` on a model

### ISSUE THREAD

**Issue by Turbo87** [rwjblue/ember-qunit-codemod#18]
> Error: You should not call `create` on a model. Instead, call `store.createRecord` with the attributes you would like to set.

I'm seeing the above error after converting some of our model tests.

**Comment by rwjblue** [comment]
Awesome. We need to fix the fixtures and update the output.

**Comment by Turbo87** [comment]
> We need to fix the fixtures and update the output.

to what exactly?

**Comment by rwjblue** [comment]
For moduleForModel we need to emit:

```
let subject = this.owner.lookup(‘service:store’).createRecord(options);
```
