### ISSUE TITLE
Support opt-in for non async/await version

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-qunit-codemod#2]
Currently the codemod always transforms `setupRenderingTest` based tests to use an `async` function (and uses `await this.render`).  Folks may be interested in avoiding async/await usage (to allow their tests to more closely emulate production usage for example).

This issue is intended to track adding an option to the codemod to avoid using `async` / `await` and instead use promises. For example:

```js
// default output
test('some nice test name', async function(assert) {
  await this.render(hbs`thing`);

  assert.equal(this.element.textContent, 'thing');
});

// with the non-async/await option enabled we would have this output:
test('some nice test name', function(assert) {
  return this.render(hbs`thing`).then(() =>{
    assert.equal(this.element.textContent, 'thing');
  });
});
```

There are some more tricky scenarios that we should ensure are tested when adding support for this, such as:

```js
// default output
test('some nice test name', async function(assert) {
  await this.render(hbs`thing`);

  assert.equal(this.element.textContent, 'thing');

  await this.clearRender();
  await this.render(hbs`other thing`);

  assert.equal(this.element.textContent, 'other thing');
});

// with the non-async/await option enabled we would have this output:
test('some nice test name', function(assert) {
  return this.render(hbs`thing`)
    .then(() =>{
      assert.equal(this.element.textContent, 'thing');

      return this.clearRender();
    })
    .then(() => {
      return this.render(hbs`other thing`);
    })
    .then(() => {
      assert.equal(this.element.textContent, 'other thing');
    });
});
```

**Comment by cibernox** [comment]
Out of curiosity, has anyone expressed this concern? It seems weird to distrust that babel will generate transpiled code will work as intended.

**Comment by rwjblue** [comment]
Nope, I haven’t had anyone bring this up yet. I mostly made the issue as a place to point folks if they were concerned. 

I’m generally not opposed to a flag or option (whatever mechanism jscodeshift provides here) that allows promise usage instead if there  are folks that need that functionality...

**Comment by rwjblue** [comment]
FYI, `jscodeshift` supports passing arbitrary options in to the rule (from [the README](https://github.com/facebook/jscodeshift#options)):

> Contains all options that have been passed to runner. This allows you to pass additional options to the transform. For example, if the CLI is called with
> 
> `$ jscodeshift -t myTransforms fileA fileB --foo=bar`
>
> options would contain {foo: 'bar'}. jscodeshift uses nomnom to parse command line options.

**Comment by rwjblue** [comment]
Going to close this for now, happy to reopen if someone wants to champion this...
