### ISSUE TITLE
Remove empty import from ember-qunit

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-qunit-codemod#36]
Currently, given the following input:

```js
import { module, test } from 'ember-qunit';
```

We emit the following output:

```js
import { module, test } from 'qunit';
import 'ember-qunit';
```

We should remove that second import when there are no import specifiers remaining...

**Comment by alexander-alvarez** [comment]
I think I could help on this -- I want to learn codemod stuff, and this seems easy enough. Anyone working on it yet?

**Comment by rwjblue** [comment]
@alexander-alvarez - Not that I know of.  The first thing to do is add a failing test case for it (in the `__testfixtures__/ember-qunit-codemod/` directory you would add both a `xxxx.input.js` and `xxxxx.output.js` file) and see if it passes.  I recently refactored some of the is code (specifically [this guard](https://github.com/rwjblue/ember-qunit-codemod/pull/47/files#diff-a85bb53309f6bb082ab8c5b3d2ca75f4R76)) and it might have fixed this already...

**Comment by rwjblue** [comment]
Even if it is already fixed, we should add the test cases to ensure we don't regress as we do other refactorings here...
