### ISSUE TITLE
Only rewrite `this.register` within known test/module types

### ISSUE THREAD

**Issue by rwjblue** [rwjblue/ember-qunit-codemod#37]
Given:

```js
import moduleForLol from '../helpers/module-for-lol';
import { test } from 'ember-qunit';

moduleForLol('asdf', {
  beforeEach() {
    this.register('helper:foo', Ember.Helper.helper(function() { }));
  }
});
```

We emit:

```js
import { module, test } from 'qunit';
import moduleForLol from '../helpers/module-for-lol';

moduleForLol('asdf', {
  beforeEach() {
    this.owner.register('helper:foo', Ember.Helper.helper(function() { }));
  }
});

```

We should not rewrite `this.register` usage universally, it should only be rewritten inside of `test` invocations, and methods passed into `moduleFor{Component,Model,}` in the options hash.

**Comment by alexander-alvarez** [comment]
Isn't this something you'd want to be applied to all of these functions?
>   updateEmberTestHelperImports();
  updateModuleForToNestedModule();
  updateLookupCalls();
  updateRegisterCalls();
  updateInjectCalls();

which could probably supercede what I did in https://github.com/rwjblue/ember-qunit-codemod/pull/49/files

Here's something I had in mind
https://github.com/rwjblue/ember-qunit-codemod/compare/master...alexander-alvarez:only-run-in-modules

still struggling with `jscodeshift` though as it's poorly documented.
