### ISSUE TITLE
Support `moduleForAcceptance`

### ISSUE THREAD

**Issue by dzbo** [rwjblue/ember-qunit-codemod#60]
I see that current support modules are:

```
const POSSIBLE_MODULES = [
    { expression: { callee: { name: 'module' } } },
    { expression: { callee: { name: 'moduleFor' } } },
    { expression: { callee: { name: 'moduleForComponent' } } },
    { expression: { callee: { name: 'moduleForModel' } } },
  ];
```

Is there plan to support `moduleForAcceptance`, so that acceptance tests can also be modified?

**Comment by rwjblue** [comment]
Yep, I’m working on another RFC to have acceptance tests to run through ember-qunit / ember-test-helpers (current code for acceptance tests is globals based and provided by ember itself). 

I’m generally trying to keep this codemod focused on things supported by ember-qunit (which does not include acceptance tests just yet). I’d hate to migrate the current `moduleForAcceptance` tests to another format _before_ the RFC is proposed with their final setup. 

I’ll try to chime in here with a link to the RFC once I have it proposed.

**Comment by rwjblue** [comment]
Submitted the RFC over here https://github.com/emberjs/rfcs/pull/268

**Comment by rwjblue** [comment]
RFC is in final comment period.  Hopefully we can land it in the next couple of weeks...

**Comment by snewcomer** [comment]
@rwjblue is the acceptance test api solidified enough to start on the codemod for acceptance tests?  Is there anywhere I can help with that?

**Comment by xomaczar** [comment]
@rwjblue ^^

**Comment by rwjblue** [comment]
https://github.com/rwjblue/ember-qunit-codemod/pull/73
