### ISSUE TITLE
More edgecases :D

### ISSUE THREAD

**Issue by alexander-alvarez** [rwjblue/ember-qunit-codemod#67]
Just wanted to give some context as to the barrage of PRs and issues.
Ran the codemod against my repo and came up with these edge cases (https://github.com/rwjblue/ember-qunit-codemod/pull/63, https://github.com/rwjblue/ember-qunit-codemod/issues/64, https://github.com/rwjblue/ember-qunit-codemod/pull/65, https://github.com/rwjblue/ember-qunit-codemod/pull/66).

I found that in describing issues, I might have well simply added testcases, so instead of opening issues where I knew the expected outcome, I wrote failing testcases and opened PRs (with the hope that someone may get to them quicker than I)

Thanks for the great codemod. I'll likely eventually get to them, but more than happy to see them magically go away :smiley:

**Comment by rwjblue** [comment]
Tracking individual issues separately so I'm going to close this issue for now...
