### ISSUE TITLE
Bump recast to 0.5.0

### ISSUE THREAD

**Issue by chriskrycho** [rwjblue/ember-qunit-codemod#74]
It'd be awesome if this used the latest version of jscodeshift, which includes support for TypeScript and therefore would (at least in principle) make this viable for TypeScript codebases. (I'll try to open a PR with it shortly.)

**Comment by chriskrycho** [comment]
Update: that won't help; jscodeshift has the ability *in principle* but not at all *in practice* to do this.

**Comment by rwjblue** [comment]
I think that this issue will be resolved by https://github.com/rwjblue/ember-qunit-codemod/pull/88...
