### ISSUE TITLE
Handle already-existing top-level `module`

### ISSUE THREAD

**Issue by chriskrycho** [rwjblue/ember-qunit-codemod#90]
Input

```js
module('something', { beforeEach() {}, afterEach() {} }, function() {
  moduleForAcceptance('nested', { beforeEach() {}, afterEach() {} }, function() {
  });
});
```

Desired output:

```js
module('something', function(hooks) {
  hooks.beforeEach(function(assert) {})
  hooks.afterEach(function(assert) {})

  module('nested', function(hooks) {
    setupApplicationTest(hooks);
    hooks.beforeEach(function(assert) {})
    hooks.afterEach(function(assert) {})
  });
});
```

Actual output is unchanged from the input, other than removing the `moduleForAcceptance` input.

**Comment by dwickern** [comment]
Should it shadow `hooks` or just keep the outermost one?

**Comment by chriskrycho** [comment]
@dwickern I think it should *probably* keep the innermost one, actually? But not positive there.

**Comment by chriskrycho** [comment]
Actually, on further consideration, we need to support *both* working correctly, because our app (and others, I'm guessing) have `beforeEach` running in both contexts.
